import { motion } from 'framer-motion'
import { useInView } from 'framer-motion'
import { useRef } from 'react'
import { Terminal, Settings, Play, GitBranch } from 'lucide-react'
import { CodeBlock } from './ui/CodeBlock'

const steps = [
  {
    icon: GitBranch,
    title: 'Clone & Install',
    desc: 'Clone the repository and install dependencies with npm.',
    color: '#4f6eff',
  },
  {
    icon: Settings,
    title: 'Run Setup Wizard',
    desc: 'The interactive wizard walks you through channel config, LLM provider selection, and YubiKey registration.',
    color: '#10b981',
  },
  {
    icon: Play,
    title: 'Start Argos',
    desc: 'Launch in dev mode or production. Open the dashboard at localhost:3000 to see your first proposals.',
    color: '#ef4444',
  },
]

const cloneCode = `# Clone and install
git clone https://github.com/reejakdev/argosbot
cd argosbot
npm install

# Run interactive setup wizard
npm run setup

# Start in development mode
npm run dev

# Or build and run in production
npm run build
npm start`

const configExampleCode = `// ~/.argos/config.json (generated by wizard)
{
  "llm": {
    "provider": "anthropic",
    "model": "claude-opus-4-5",
    "apiKey": "sk-ant-..."
  },
  "llmLocal": {
    "provider": "ollama",
    "model": "llama3.2",
    "baseUrl": "http://localhost:11434"
  },
  "channels": {
    "telegram": {
      "enabled": true,
      "apiId": 12345678,
      "apiHash": "abc123..."
    },
    "email": {
      "enabled": true,
      "imap": {
        "host": "imap.gmail.com",
        "port": 993
      }
    }
  },
  "webApp": {
    "port": 3000,
    "origin": "http://localhost:3000"
  },
  "readOnly": true
}`

export default function Setup() {
  const ref = useRef(null)
  const inView = useInView(ref, { once: true })

  return (
    <section
      id="setup"
      className="py-24"
      style={{ borderTop: '1px solid rgba(79,110,255,0.08)' }}
    >
      <div className="max-w-7xl mx-auto px-6">
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 20 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          className="mb-14"
        >
          <div className="section-label mb-3">Setup</div>
          <h2 className="text-3xl lg:text-4xl font-bold text-text mb-4">
            Running in{' '}
            <span className="gradient-text">under 5 minutes</span>
          </h2>
          <p className="text-text2 max-w-2xl leading-relaxed">
            Argos ships with an interactive setup wizard that handles channel configuration,
            LLM selection, and authentication setup. No manual config file editing required.
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-12 items-start">
          {/* Left: Steps */}
          <div>
            <div className="space-y-5 mb-8">
              {steps.map((step, i) => {
                const Icon = step.icon
                return (
                  <motion.div
                    key={step.title}
                    initial={{ opacity: 0, x: -30 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.15 }}
                    className="flex items-start gap-4"
                  >
                    <div className="flex flex-col items-center flex-shrink-0">
                      <div
                        className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0"
                        style={{
                          background: `${step.color}12`,
                          border: `1px solid ${step.color}25`,
                        }}
                      >
                        <Icon size={18} style={{ color: step.color }} />
                      </div>
                      {i < steps.length - 1 && (
                        <div
                          className="w-px h-8 mt-2"
                          style={{ background: `linear-gradient(to bottom, ${step.color}35, transparent)` }}
                        />
                      )}
                    </div>
                    <div className="pt-1">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-xs font-medium text-text2/40 tracking-wide">STEP {i + 1}</span>
                        <h3 className="font-semibold text-text">{step.title}</h3>
                      </div>
                      <p className="text-text2 text-sm leading-relaxed">{step.desc}</p>
                    </div>
                  </motion.div>
                )
              })}
            </div>

            {/* System requirements */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.4 }}
              className="rounded-lg p-5"
              style={{
                background: 'var(--surface)',
                border: '1px solid var(--border)',
                boxShadow: '0 4px 24px rgba(0,0,0,0.3)',
              }}
            >
              <div className="flex items-center gap-2 mb-4">
                <Terminal size={14} style={{ color: '#7b96ff' }} />
                <span className="text-xs font-semibold tracking-wide" style={{ color: '#7b96ff' }}>SYSTEM REQUIREMENTS</span>
              </div>
              <div className="space-y-2">
                {[
                  { label: 'Runtime', value: 'Node.js >= 22' },
                  { label: 'Platform', value: 'macOS / Linux / Windows WSL' },
                  { label: 'RAM (no local model)', value: '512 MB minimum' },
                  { label: 'RAM (with 7B local model)', value: '8 GB recommended' },
                  { label: 'Storage', value: '500 MB + model size' },
                  { label: 'Local model (optional)', value: 'Ollama or LM Studio' },
                ].map((req) => (
                  <div key={req.label} className="flex items-center justify-between text-sm">
                    <span className="text-text2">{req.label}</span>
                    <span className="font-mono text-xs" style={{ color: '#7b96ff' }}>{req.value}</span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>

          {/* Right: Code blocks */}
          <div className="space-y-4">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <CodeBlock code={cloneCode} language="bash" title="terminal" />
            </motion.div>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.2 }}
            >
              <CodeBlock code={configExampleCode} language="json" title="~/.argos/config.json" />
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  )
}
